### PR TITLE
Fix workspace cleanup issue and add comprehensive testing infrastructure

### LINKED ISSUE #95: `workspace` removes workspace on test failure
## Current behaviour

`workspace` removes test directory on test failure.

## Expected behaviour

`workspace` removes only test directories for successful tests. Workspaces for failed test directories are preserved

## Context

This is a regression introduced in: https://github.com/input-output-hk/hedgehog-extras/commit/3ffcb855e77e658bff1060db54a882ee911446f4

Note that the `bracket` will always execute new `fini` function.

### PR DESCRIPTION
**Pull request by newhoggy**
## Summary

This PR fixes issue #95 where workspace directories were being removed even when tests failed, making debugging difficult. The solution replaces bracket-based cleanup with explicit error handling and includes comprehensive test coverage for all workspace scenarios plus Claude IDE integration for enhanced development workflow.

### 🔧 Bug Fix - Workspace Cleanup (Fixes #95) 
- **Fix workspace preservation on test failure**: Replace `bracket` with `catchAssertion` in `workspaceWithConfig` for proper error handling
- **Preserve directories for debugging**: Workspace directories are now preserved when tests fail, pure exceptions occur, or IO exceptions are thrown
- **Conditional cleanup logic**: Clean up directories only on successful test completion (unless `keepWorkspace=True`)
- **Add MonadAssertion constraint**: Required for proper error handling in workspace functions
- **Enhanced error handling**: Supports both assertion failures and all types of exceptions

### 🧪 Comprehensive Testing Infrastructure  
- **Add WorkspaceSpec test module** with 8 comprehensive test scenarios:
  - Success case with `keepWorkspace=False` (cleanup)
  - Assertion failure with `keepWorkspace=False` (preserve) 
  - Pure exception with `keepWorkspace=False` (preserve)
  - IO exception with `keepWorkspace=False` (preserve)
  - Success case with `keepWorkspace=True` (always preserve)
  - Assertion failure with `keepWorkspace=True` (always preserve)
  - Pure exception with `keepWorkspace=True` (always preserve) 
  - IO exception with `keepWorkspace=True` (always preserve)
- **Extend Base module** with improved `workspaceWithConfig` function
- **Add directory dependency** to support filesystem operations in tests
- All tests include proper cleanup and verification of expected behavior

### 🛠️ Claude IDE Integration & Build Improvements
- **Add three command templates** for git workflow automation:
  - `commit-twiddle`: automated commit message improvement using omni-dev
  - `pr-create`: automated pull request creation with template support  
  - `pr-update`: automated pull request updates based on branch changes
- **Update .gitignore** to exclude Claude IDE local settings files

## Technical Details

The core fix replaces the problematic `bracket` pattern:
```haskell
-- Old (problematic):
bracket init fini $ \ws -> f ws

-- New (correct):
result <- catchAssertion (fmap Right (f ws)) (return . Left)
case result of
  Right _ -> unless keepWorkspace $ cleanup
  Left assertion -> do
    unless keepWorkspace $ annotate "Preserving for debug"
    throwAssertion assertion
```

This ensures workspace directories are preserved for debugging when tests fail while maintaining proper cleanup on success.

## Test Plan

- [x] Verify all 8 WorkspaceSpec tests pass covering every scenario combination
- [x] Confirm workspace directories are preserved when tests fail for debugging
- [x] Confirm workspace directories are preserved on pure exceptions  
- [x] Confirm workspace directories are preserved on IO exceptions
- [x] Confirm workspace directories are cleaned up when tests succeed (keepWorkspace=False)
- [x] Test `keepWorkspace=True` preserves directories in all cases
- [x] Ensure no Claude IDE local settings are accidentally committed
- [x] Verify GHC 9.8 builds successfully in CI
- [x] All existing tests continue to pass

## Context

The workspace cleanup issue was caused by `bracket` always executing cleanup in its finalizer, regardless of whether the test succeeded or failed. This made debugging failed tests difficult because the workspace directory containing test artifacts was always removed.

The new implementation uses explicit error handling with `catchAssertion` to distinguish between success and failure cases, preserving directories only when needed for debugging while maintaining proper cleanup behavior.

Fixes #95

### CODE REVIEW

**Comment by carbolymer** [comment]
I'm not a fan of AI-generated changelogs:

> Fix workspace preservation on test failure: Replace bracket with explicit error handling in workspaceWithConfig
> Preserve directories for debugging: Workspace directories are now preserved when tests fail
> Conditional cleanup logic: Clean up directories only on successful test completion (unless keepWorkspace=True)

This is too watered down and can be a single bullet point.

**Review by carbolymer — DISMISSED** [review]
https://github.com/input-output-hk/hedgehog-extras/pull/97/commits/facc15558655bd964c93fd6764c01ccc5cd53e44#r2318996705

File: src/Hedgehog/Extras/Test/Base.hs [hunk 1]
```diff
@@ -184,23 +185,54 @@ workspace
...
+  -> m ()
+workspaceWithConfig keepWorkspace prefixPath f = withFrozenCallStack $ do
+  ws <- do
+    systemTemp <- H.evalIO IO.getCanonicalTemporaryDirectory
+    H.evalIO $ IO.createTempDirectory systemTemp $ prefixPath <> "-test"
+  
+  H.annotate $ "Workspace: " <> ws
+  H.evalIO $ IO.writeFile (ws </> "module") callerModuleName
+  
+  result <- H.catchAssertion (fmap Right (f ws)) (return . Left)
```
[the remark this answers is not in the document]
Comment (newhoggy) [reply src/Hedgehog/Extras/Test/Base.hs:224]: Added additional test scenarios.

File: src/Hedgehog/Extras/Test/Base.hs [hunk 2]
```diff
@@ -181,26 +182,59 @@ expectFailureWith checkFailure prop = GHC.withFrozenCallStack $ do
...
+-- The directory will be deleted if the block succeeds, but left behind if
+-- the block fails (unless keepWorkspace is True, in which case it's always preserved).
+workspaceWithConfig
+  :: HasCallStack
+  => MonadCatch m
+  => MonadBaseControl IO m
+  => MonadResource m
+  => MonadTest m
+  => H.MonadAssertion m
+  => Bool  -- ^ keepWorkspace: if True, always preserve workspace; if False, delete on success only
```
Comment (carbolymer) [inline src/Hedgehog/Extras/Test/Base.hs:212]: Boolean blindness - this should be a sum type instead of bool.

File: test/Hedgehog/Extras/Test/WorkspaceSpec.hs [hunk 3]
```diff
@@ -0,0 +1,248 @@
...
+  -- This workspace operation will succeed
+  workspaceWithConfig False "test-success" $ \ws -> do
+    liftIO $ writeIORef workspacePath (Just ws)
+    -- Successful operation - no failing assertions
+    True === True
+  
+  -- After successful completion, workspace should be removed
+  maybePath <- liftIO $ readIORef workspacePath
+  case maybePath of
+    Nothing -> failure
```
Comment (carbolymer) [inline test/Hedgehog/Extras/Test/WorkspaceSpec.hs:36]: This failure is too cryptic. Can you add annotate saying what went wrong?

**Review by carbolymer — APPROVED** [review]
